{{- if and .Values.jwt.create (not (eq .Values.jwt.secret "")) }} 
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocodb.jwtSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "nocodb.jwtSecretKey" . }}: {{ .Values.jwt.secret | b64enc | quote }}
{{- end }}
