apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oaf-odoo-data-migration.fullname" . }}-config
  labels:
    {{- include "oaf-odoo-data-migration.labels" . | nindent 4 }}
data:
  logging.conf: |
    [loggers]
    keys=root

    [handlers]
    keys=consoleHandler

    [formatters]
    keys=simpleFormatter

    [logger_root]
    level={{ .Values.logging.level | default "INFO" }}
    handlers=consoleHandler

    [handler_consoleHandler]
    class=StreamHandler
    level={{ .Values.logging.level | default "INFO" }}
    formatter=simpleFormatter
    args=(sys.stdout,)

    [formatter_simpleFormatter]
    format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
