{{- if .Values.odoo.useSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oaf-odoo-data-migration.fullname" . }}-secrets
  labels:
    {{- include "oaf-odoo-data-migration.labels" . | nindent 4 }}
type: Opaque
data:
  odoo-url: {{ .Values.odoo.url | b64enc }}
  odoo-database: {{ .Values.odoo.database | b64enc }}
  odoo-username: {{ .Values.odoo.username | b64enc }}
  odoo-password: {{ .Values.odoo.password | b64enc }}
{{- end }}
